name: Wisecow Application

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
     
      - name: containeration
        run: docker build -t ajjurathod1998/wisecow .

      - name: docker login
        run: docker login -u ajjurathod1998 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: pushing to dockerhub
        run : docker push ajjurathod1998/wisecow
        env:
            DOCKER_CLI_ACI: 1
