name: Wisecow Application

on:
  push:
    branches:
      - main


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
     
      - name: containeration
        run: docker build -t ajjurathod1998/wisecow .

      - name: docker login
        run: docker login -u ajjurathod1998 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: pushing to dockerhub
        run : docker push ajjurathod1998/wisecow
        env:
            DOCKER_CLI_ACI: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
      
     - name: Set up kubectl
       uses: setup-kubectl@v1
       with:
         version: 'latest'
         
     - name: Create .kube directory
       run: mkdir -p $HOME/.kube  
       
     - name: Set up Kubeconfig
       run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config |base64
       
     - name: Verify kubeconfig
       run: | 
        kubectl config view
        kubectl cluster-info
        kubectl get nodes


     - name: Deploy to Kubernetes 
       run: |
         kubectl apply -f kubernetes/deployment.yml --validate=false
         kubectl apply -f kubernetes/service.yml --validate=false 
