name: Wisecow Application

on:
  push:
    branches:
      - main


jobs:
  build:
    name: build 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
     
      - name: containeration
        run: docker build -t ajjurathod1998/wisecow . 

      - name: docker login
        run: docker login -u ajjurathod1998 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: pushing to dockerhub 
        run : docker push ajjurathod1998/wisecow
        env:
            DOCKER_CLI_ACI: 1
  deploy:
      runs-on: ubuntu-latest
      needs: build 
      steps:
        - name: Set up Kubernetes config
          env:
           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          run: |
           mkdir -p $HOME/.kube
           echo "$KUBE_CONFIG_DATA" | tr -d '\n' | base64 --decode > $HOME/.kube/config
           cat $HOME/.kube/config # For debugging, you can remove this line after confirming the content

        - name: Apply Kubernetes manifests
          run: kubectl apply -f deployment.yaml
